### ISSUE TITLE
Questions about return attention score

### ISSUE THREAD

**Issue by YueyuanKang** [4AI/AGN#4]
I am interested in and reproducing your model. 
But I really confused when I want to return the attention score, I change the parameter in the Attention part return_attention to True. But it always raised warnings. would you please tell me is there another setting I need to change?

Thanks a lot!

![image](https://user-images.githubusercontent.com/77316342/142370000-44648fe1-8c44-4c6b-88b6-768e0bb1b18a.png)

**Comment by SeanLee97** [comment]
Hi @YueyuanKang, I have refactored the code in [refactor branch](https://github.com/4AI/AGN/tree/refactor):

1. substitute bert4keras with langml to load BERTs
2. support attention visualization. (It's slightly different from the paper, we visualize 2D rather than 1D attention in this edition.)

Although this branch is available to run, I am still working to improve the code.  You can try it after the code merge in the main branch if you aren't in a hurry.

**Comment by SeanLee97** [comment]
I've fixed the problem and merged it to the main branch.

**Comment by YueyuanKang** [comment]
Thanks I will try it later.
